version: 2
jobs:
  build:
    branches:
      only:
        - Assignment5
        - master
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y
          
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Build Artifact
          command: |
            cd trailv1
            pwd
            ls -al
            mvn clean install -DskipTests
            cd target/
            ls -al
            cd ../..
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            pwd
            cd ..
            pwd
            ls -al
    
